name: Run PR checks
on:
  push:
  workflow_dispatch:

env:
  VITE_PORT: 3000
  API_PORT: 3001
  VITE_API_URL: 'http://localhost:3001'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: npm ci

  unit-test:
    needs: [install-dependencies]
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.8
        with:
          runTests: false
      - name: unit-test
        run: npm run test:coverage

  lint:
    needs: install-dependencies
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.8
        with:
          runTests: false
      - name: lint
        run: npm run lint

  typecheck:
    needs: install-dependencies
    name: Run typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        uses: cypress-io/github-action@v6.7.8
        with:
          runTests: false
      - name: typecheck
        run: npm run typecheck
